// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhRBnr5N6jIFs5VEBIM5RbOqroFZAgxgI',
    appId: '1:767290362790:web:de149908da2847dd051d67',
    messagingSenderId: '767290362790',
    projectId: 'equipo-9f22f',
    authDomain: 'equipo-9f22f.firebaseapp.com',
    storageBucket: 'equipo-9f22f.appspot.com',
    measurementId: 'G-SDR8C8EQEC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCENAZUFahiaVFO8BTkbVMjFBCDU7f3vzI',
    appId: '1:767290362790:android:ac4e816a7c1d43ae051d67',
    messagingSenderId: '767290362790',
    projectId: 'equipo-9f22f',
    storageBucket: 'equipo-9f22f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSqjhiOeLfMSmZkg9kl_-kD4zHM5t8aX0',
    appId: '1:767290362790:ios:e06a5894db38de17051d67',
    messagingSenderId: '767290362790',
    projectId: 'equipo-9f22f',
    storageBucket: 'equipo-9f22f.appspot.com',
    iosBundleId: 'com.example.equipo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSqjhiOeLfMSmZkg9kl_-kD4zHM5t8aX0',
    appId: '1:767290362790:ios:e06a5894db38de17051d67',
    messagingSenderId: '767290362790',
    projectId: 'equipo-9f22f',
    storageBucket: 'equipo-9f22f.appspot.com',
    iosBundleId: 'com.example.equipo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhRBnr5N6jIFs5VEBIM5RbOqroFZAgxgI',
    appId: '1:767290362790:web:d6a215af8dc6f697051d67',
    messagingSenderId: '767290362790',
    projectId: 'equipo-9f22f',
    authDomain: 'equipo-9f22f.firebaseapp.com',
    storageBucket: 'equipo-9f22f.appspot.com',
    measurementId: 'G-SXBFPRDLHP',
  );
}
